-- 운영 스키마는 API 서버 저장소(spr1n6-osscontest-server)가 소유한다.
-- 이 파일은 Testcontainers 전용이며, 운영 마이그레이션과의 동기화 책임은 doc-relay 에 있다.
-- 이 파일을 근거로 운영 스키마를 변경하지 않는다.
--
-- 릴레이가 실제로 읽고 쓰는 것은 outbox_event 하나뿐이다.
-- tenant / document / document_version 은 outbox_event 의 복합 FK 와
-- INDEXING_REQUESTED 트리거를 재현하기 위한 최소 부모 테이블이다.
-- document_chunk / indexing_job / app_user 는 릴레이가 접근하지 않으므로 만들지 않는다.

CREATE TABLE tenant (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE document (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT       NOT NULL REFERENCES tenant(id),
    owner_principal_id    VARCHAR(255) NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    latest_version_no     BIGINT       NOT NULL DEFAULT 0,
    searchable_version_id BIGINT,
    deleted_at            TIMESTAMPTZ,
    purged_at             TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_document_id_tenant UNIQUE (id, tenant_id)
);

CREATE TABLE document_version (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id             BIGINT        NOT NULL REFERENCES document(id),
    version_no              BIGINT        NOT NULL,
    source_object_key       VARCHAR(1024) NOT NULL,
    original_filename       BYTEA         NOT NULL,
    mime_type               VARCHAR(100)  NOT NULL,
    file_size               BIGINT        NOT NULL,
    content_hash            VARCHAR(128)  NOT NULL,
    source_metadata         JSONB,
    extracted_metadata      JSONB,
    chunk_count             INTEGER,
    indexed_at              TIMESTAMPTZ,
    created_by_principal_id VARCHAR(255)  NOT NULL,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_document_version             UNIQUE (document_id, version_no),
    CONSTRAINT uk_document_version_id_document UNIQUE (id, document_id),
    CONSTRAINT ck_document_version_no          CHECK (version_no > 0)
);

-- 릴레이가 소유하는 유일한 테이블. spec §3 "릴레이가 기대하는 최종 형태" 와 일치해야 한다.
CREATE TABLE outbox_event (
    id                    UUID PRIMARY KEY,
    tenant_id             BIGINT      NOT NULL,
    document_id           BIGINT      NOT NULL,
    -- INDEXING_REQUESTED 는 버전 단위라 값을 가지고, DOCUMENT_DELETED 는 문서 단위라 NULL 이다.
    -- 아래 두 CHECK 가 이벤트 종류별로 값의 유무를 강제한다.
    document_version_id   BIGINT,
    event_type            VARCHAR(50) NOT NULL,
    event_schema_version  INTEGER     NOT NULL DEFAULT 1,
    payload               JSONB       NOT NULL,
    trace_id              VARCHAR(255),
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    publish_attempt_count INTEGER     NOT NULL DEFAULT 0,
    next_attempt_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_by             VARCHAR(255),
    locked_at             TIMESTAMPTZ,
    published_at          TIMESTAMPTZ,
    last_error_message    TEXT,
    retry_of_event_id     UUID,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_outbox_document_tenant
        FOREIGN KEY (document_id, tenant_id)
        REFERENCES document(id, tenant_id),
    CONSTRAINT fk_outbox_document_version
        FOREIGN KEY (document_version_id, document_id)
        REFERENCES document_version(id, document_id),
    CONSTRAINT ck_outbox_schema_version
        CHECK (event_schema_version > 0),
    CONSTRAINT ck_outbox_event_type
        CHECK (event_type IN ('INDEXING_REQUESTED', 'DOCUMENT_DELETED')),
    CONSTRAINT ck_outbox_indexing_request_target
        CHECK (event_type <> 'INDEXING_REQUESTED'
               OR document_version_id IS NOT NULL),
    CONSTRAINT ck_outbox_document_deleted_target
        CHECK (event_type <> 'DOCUMENT_DELETED'
               OR document_version_id IS NULL),
    CONSTRAINT ck_outbox_status
        CHECK (status IN ('PENDING', 'PUBLISHING', 'PUBLISHED', 'DEAD')),
    CONSTRAINT ck_outbox_publish_attempt_count
        CHECK (publish_attempt_count >= 0)
);

CREATE INDEX idx_outbox_pending ON outbox_event (next_attempt_at, id) WHERE status = 'PENDING';
CREATE INDEX idx_outbox_stuck   ON outbox_event (locked_at)           WHERE status = 'PUBLISHING';

-- 파트너 저장소의 V20260812_001__init_schema.sql 트리거와 동일하게 유지한다.
CREATE OR REPLACE FUNCTION fn_outbox_indexing_requested()
RETURNS TRIGGER AS $$
DECLARE
    v_tenant_id BIGINT;
    v_event_id  UUID;
BEGIN
    SELECT tenant_id INTO v_tenant_id FROM document WHERE id = NEW.document_id;
    v_event_id := gen_random_uuid();

    INSERT INTO outbox_event (
        id, tenant_id, document_id, document_version_id,
        event_type, event_schema_version, payload, trace_id
    )
    VALUES (
        v_event_id, v_tenant_id, NEW.document_id, NEW.id,
        'INDEXING_REQUESTED', 1,
        jsonb_build_object(
            'versionNo',       NEW.version_no,
            'sourceObjectKey', NEW.source_object_key,
            'mimeType',        NEW.mime_type,
            'fileSize',        NEW.file_size,
            'contentHash',     NEW.content_hash,
            'occurredAt',      to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
                                       'YYYY-MM-DD"T"HH24:MI:SS"Z"')
        ),
        current_setting('app.trace_id', true)
    );

    PERFORM pg_notify('outbox_event', v_event_id::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_document_version_outbox
    AFTER INSERT ON document_version
    FOR EACH ROW
    EXECUTE FUNCTION fn_outbox_indexing_requested();

-- 데모 시드 데이터
INSERT INTO tenant (name) VALUES ('acme');
INSERT INTO document (tenant_id, owner_principal_id, title)
VALUES (1, 'USER:1', 'demo-doc');
